Added a new step to check if JaCoCo exec file is created before generating JaCoCo report.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -52,6 +52,15 @@ jobs:
         run: |
           java -javaagent:lib/org.jacoco.agent-0.8.12-runtime.jar=destfile=target/jacoco.exec,output=tcpserver -cp lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar:bin org.junit.runner.JUnitCore MainTest
 
+      - name: Check if JaCoCo exec file is created
+        run: |
+          if [ -f target/jacoco.exec ]; then
+            echo "JaCoCo exec file found."
+          else
+            echo "JaCoCo exec file not found."
+            exit 1
+          fi
+
       - name: Generate JaCoCo Report
         run: |
           java -cp lib/org.jacoco.cli-0.8.12.jar:lib/org.jacoco.core-0.8.12.jar:lib/org.jacoco.report-0.8.12.jar:lib/args4j-2.33.jar:bin org.jacoco.cli.internal.Main report target/jacoco.exec --classfiles bin --sourcefiles src --html target/jacoco-html --xml target/jacoco.xml --csv target/jacoco.csv
